#!/bin/bash

#adm90 - verifcador
#adm1 - CRIAR USUARIOS
#adm21 - CRIAR USUARIO TEMPORARIO OPENSSH
#adm22 - CRIAR USUARIO TEMPORARIO DROPBEAR
#adm3 - REDEFINIR USUARIOS
#adm4 - REMOVER USUARIOS
#adm5 - INFORMACOES USUARIOS
#adm61 - MONITORAR USUARIOS OPENSSH
#adm62 - MONITORAR USUARIOS DROPBEAR
#adm7 - REMOVER USUARIOS VENCIDOS
#adm81 - MUDAR BANNER OPENSSH
#adm82 - MUDAR BANNER DROPBEAR
#banner - BANNER ESCONDIDO
#--------------------------------------------------------------#

if [ "$1" = "adm1" ]; then
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[1;32m----------------------------------\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo -e "\033[1;31m $u \033[0m"
done
echo -e "\033[1;32m----------------------------------\033[0m"
rm -rf /tmp/ussh
#
echo -e "\033[1;31mCreador De Usuario @MRX470"
echo -e "\033[1;32mNombre nuevo de usuario:\033[0;37m"; read -p " " name
if [ "$name" = "" ]; then
echo -e "\033[1;31mNada fue Digitado\033[0m"
exit
fi
if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
then
echo -e "\033[1;31mUsuario $name ya existe\033[0m"
exit
fi
echo -e "\033[1;32mContraseña para o usuario $name:\033[0;37m"; read -p " " pass
echo -e "\033[1;32mCuantos dias usuario $name deve durar:\033[0;37m"; read -p " " daysrnf
echo -e "\033[1;32mCuantas conexiones?:\033[0;37m"; read -p " " limit
echo -e "\033[0m"
valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
datexp=$(date "+%d/%m/%Y" -d " +$daysrnf days")
useradd -M -s /bin/false $name -e $valid
(echo $pass; echo $pass)|passwd $name 2>/dev/null
touch /etc/adm/usuarios/$name
echo "contraseña: $pass" >> /etc/adm/usuarios/$name
echo "limite: $limit" >> /etc/adm/usuarios/$name
echo "fecha: $valid" >> /etc/adm/usuarios/$name
echo -e "\033[1;36mUsuario: \033[1;37m$name"
echo -e "\033[1;36mContraseñaa: \033[1;37m$pass"
echo -e "\033[1;36mLimite: \033[1;37m$limit"
echo -e "\033[1;36mValido: \033[1;37m$datexp"
echo -e "\033[1;36mCreado Con Exito \033[0m"
exit
fi

#--------------------------------------------------------------#

tmpusr () {
time="$1"
timer=$(( $time * 60 ))
timer2="'$timer's"
echo "#!/bin/bash
sleep $timer2
kill"' $(ps -u '"$2 |awk '{print"' $1'"}') 1> /dev/null 2> /dev/null
userdel --force $2
rm -rf /tmp/$2
exit" > /tmp/$2
}

tmpusr2 () {
time="$1"
timer=$(( $time * 60 ))
timer2="'$timer's"
echo "#!/bin/bash
sleep $timer2
kill=$(dropb | grep "$2" | awk '{print $2}')
kill $kill
userdel --force $2
rm -rf /tmp/$2
exit" > /tmp/$2
}

if [ "$1" = "adm21" ]; then
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[1;32m----------------------------------\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo -e "\033[1;31m $u \033[0m"
done
echo -e "\033[1;32m----------------------------------\033[0m"
rm -rf /tmp/ussh
#
echo -e "\033[1;32mNome do usuario:\033[0;37m"; read -p " " name
if [[ -z $name ]]
then
echo "Nao Foi digitado Nenhum Usuario"
exit
fi
if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
then
echo -e "\033[1;31mUsuario $name ja existe\033[0m"
exit
fi
echo -e "\033[1;32mSenha para o usuario $name:\033[0;37m"; read -p " " pass
echo -e "\033[1;32mTempo de Duração Em Minutos:\033[0;37m"; read -p " " tmp
if [ "$tmp" = "" ]; then
tmp="30"
echo -e "\033[1;32mFoi Definido 30 minutos!\033[0m"
sleep 2s
fi
useradd -M -s /bin/false $name
(echo $pass; echo $pass)|passwd $name 2>/dev/null
touch /tmp/$name
tmpusr $tmp $name
chmod 777 /tmp/$name
touch /tmp/cmd
chmod 777 /tmp/cmd
echo "nohup /tmp/$name & >/dev/null" > /tmp/cmd
/tmp/cmd 2>/dev/null 1>/dev/null
rm -rf /tmp/cmd
touch /etc/adm/usuarios/$name
echo "senha: $pass" >> /etc/adm/usuarios/$name
echo "data: ($tmp)Minutos" >> /etc/adm/usuarios/$name
echo -e "\033[1;36mUsuario Criado!\033[0m"
echo -e ""
echo -e "\033[1;36mUsuario: \033[0m$name"
echo -e "\033[1;36mSenha: \033[0m$pass"
echo -e "\033[1;36mMinutos de Duracao: \033[0m$tmp"
exit
fi

if [ "$1" = "adm22" ]; then
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[1;32m----------------------------------\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo -e "\033[1;31m $u \033[0m"
done
echo -e "\033[1;32m----------------------------------\033[0m"
rm -rf /tmp/ussh
#
echo -e "\033[1;32mNombre de usuario:\033[0;37m"; read -p " " name
if [[ -z $name ]]
then
echo "Nada Fue digitado de Usuario"
exit
fi
if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
then
echo -e "\033[1;31mUsuario $name ya existe\033[0m"
exit
fi
echo -e "\033[1;32mContraseña para o usuario $name:\033[0;37m"; read -p " " pass
echo -e "\033[1;32mTiempo de Duracion En Minutos:\033[0;37m"; read -p " " tmp
if [ "$tmp" = "" ]; then
tmp="30"
echo -e "\033[1;32mFue Definido 30 minutos!\033[0m"
sleep 2s
fi
useradd -M -s /bin/false $name
(echo $pass; echo $pass)|passwd $name 2>/dev/null
touch /tmp/$name
tmpusr2 $tmp $name
chmod 777 /tmp/$name
touch /tmp/cmd
chmod 777 /tmp/cmd
echo "nohup /tmp/$name & >/dev/null" > /tmp/cmd
/tmp/cmd 2>/dev/null 1>/dev/null
rm -rf /tmp/cmd
touch /etc/adm/usuarios/$name
echo "senha: $pass" >> /etc/adm/usuarios/$name
echo "data: ($tmp)Minutos" >> /etc/adm/usuarios/$name
echo -e "\033[1;36mUsuario Criado!\033[0m"
echo -e ""
echo -e "\033[1;36mUsuario: \033[0m$name"
echo -e "\033[1;36mSenha: \033[0m$pass"
echo -e "\033[1;36mMinutos de Duracao: \033[0m$tmp"
exit
fi

#--------------------------------------------------------------#

if [ "$1" = "adm3" ]; then
if [ -e /root/usr ]; then
rm -rf /root/usr
fi
touch /root/usr
s="1"
cat /etc/passwd |grep -v ovpn > /tmp/ussh
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[1;32m----------------------------------\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /tmp/ussh |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo "$s $u" >> /root/usr
echo -e "\033[1;31m[ $s ]\033[1;33m $u \033[0m"
s=$(($s + 1))
done
echo -e "\033[1;32m----------------------------------\033[0m"
ussrs=$(($s - 1))
echo -e "\033[1;36mSelecione O Usuario, O Escriba su Nombre!\033[0m"
read -p "NOME ou [ 1 - $ussrs ]: " client
if [ "$client" = "" ]
then
echo -e "\033[1;31mNingun Usuario Fue Selecionado\033[0m"
exit
fi
if [ "$client" -le "$ussrs" ] 1> /dev/null 2> /dev/null
then
sed -n $client' p;' /root/usr | awk '{print $2}' > /etc/adm/name
clientname=$(head -n 1 /etc/adm/name)
rm -rf /etc/adm/name
rm -rf /root/usr
 else
if cat /etc/passwd |grep $client: > /dev/null
 then
clientname="$client"
rm -rf /root/usr
 else
 echo "Usuario $client No Existe"
sleep 5s
rm -rf /root/usr
 exit
 fi
fi
##
namer="$clientname"
echo -e "\033[1;36mQue desea Redefinir?"
echo -e "\033[1;33m
[ 1 ] - Numero de logins de\033[1;31m $namer \033[1;33m?
[ 2 ] - Data de expiraçao de\033[1;31m $namer \033[1;33m?
[ 3 ] - Mudar senha de\033[1;31m $namer \033[1;33m?"
echo -e "\033[1;36m"
read -p "[1-3]: " opt
echo -e "\033[0m"

if [ "$opt" = "1" ]; then
read -p "Cual es el nuevo limite de logins: " liml
if [ "$liml" = "" ]; then
echo "Limite No Alterado!"
exit
fi
var1=$(cat /etc/adm/usuarios/$namer | grep "contraseña")
var2=$(cat /etc/adm/usuarios/$namer | grep "fecha")
echo -e "$var1
$var2
limite: $liml" > /etc/adm/usuarios/$namer
echo -e "Limite Alterado!"
exit
fi

if [ "$opt" = "2" ]; then
echo -e "\033[1;36mCuantos Dias Debe Durar?\033[0m"
read -p ": " date
if [ "$date" = "" ]; then
echo "Fecha no Alterada!"
exit
fi
datexp=$(date "+%d/%m/%Y" -d " + $date days")
valid=$(date '+%C%y-%m-%d' -d " + $date days")
chage -E $valid $namer 2> /dev/null
echo -e "Alterado!"
var1=$(cat /etc/adm/usuarios/$namer | grep -v "data")
echo -e "$var1" > /etc/adm/usuarios/$namer
echo -e "Fecha: $valid" >> /etc/adm/usuarios/$namer
echo -e "Fecha Alterada!"
echo -e "\033[1;31mUsuario: $namer
Date: $datexp\033[0m"
exit
fi

if [ "$opt" = "3" ]; then
read -p "Cual es la nueva contraseña para $namer: " senha
if [ "$senha" = "" ]; then
echo "Contraseña No Alterada!"
exit
fi
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
var1=$(cat /etc/adm/usuarios/$namer | grep -v "senha")
echo -e "$var1" > /etc/adm/usuarios/$namer
echo -e "Contraseña: $senha" >> /etc/adm/usuarios/$namer
echo "Nueva Contraseña aplicada"
exit
fi
case $opt in
*)
echo -e "No fue seleccionada ninguna opcion!"
;;
esac
fi

#--------------------------------------------------------------#

if [ "$1" = "adm4" ]; then
echo -e "\033[41;1;37mRemover Usuarios\033[0m"
echo -e "\033[1;36m
[ 1 ] - Eliminar 1 Usuario
[ 2 ] - Eliminar Todos Usuarios\033[0m"
read -p "[1-2]: " opc
case $opc in
1)
;;
2)
;;
*)
echo -e "Opcion Invalida"
exit
;;
esac
if [ "$opc" = "1" ]; then
 if [ -e /root/usr ]; then
rm -rf /root/usr
 fi
touch /root/usr
s="1"
cat /etc/passwd |grep -v ovpn > /tmp/ussh
echo -e "\033[1;32m----------------------------------\033[0m"
echo -e "\033[1;31mUSUARIOS\033[0m"
echo -e "\033[1;32m----------------------------------\033[0m"
for u in `awk -F : '$3 > 900 { print $1 }' /tmp/ussh |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo "$s $u" >> /root/usr
echo -e "\033[1;31m[ $s ]\033[1;33m $u \033[0m"
s=$(($s + 1))
done
echo -e "\033[1;32m----------------------------------\033[0m"
ussrs=$(($s - 1))
echo -e "\033[1;36mSelecione O Usuario, O Escriba su nombre!\033[0m"
read -p "Nombre [ 1 - $ussrs ]: " client
 if [ "$client" = "" ]
then
echo -e "\033[1;31mNingun Usuario Fue Selecionado\033[0m"
exit
 fi
 if [ "$client" -le "$ussrs" ] 1> /dev/null 2> /dev/null
then
sed -n $client' p;' /root/usr | awk '{print $2}' > /etc/adm/name
clientname=$(head -n 1 /etc/adm/name)
rm -rf /etc/adm/name
rm -rf /root/usr
 else
 if cat /etc/passwd |grep $client: > /dev/null
then
clientname="$client"
rm -rf /root/usr
else
echo "Usuario $client No Existe"
sleep 5s
rm -rf /root/usr
 exit
  fi
 fi
#
name="$clientname"
 userdel --force $name > /dev/null 2>/dev/null
kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
kill=$(dropb | grep "$name" | awk '{print $2}')
if [ "$kill" != "" ]; then
kill $kill
fi
if [ -e /etc/adm/usuarios/$name ]; then
rm -rf /etc/adm/usuarios/$name
fi
echo -e "\033[1;32m-----------------------------\033[0m"
echo -e "$name Removido\033[0m"
echo -e "\033[1;32m-----------------------------\033[0m"
 exit
fi

if [ "$opc" = "2" ]; then
cat /etc/passwd |grep -v ovpn > /tmp/ussh
for name in `awk -F : '$3 > 900 { print $1 }' /tmp/ussh |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
userdel --force $name > /dev/null 2>&1
kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}`  > /dev/null 2>&1
kill=$(dropb | grep "$name" | awk '{print $2}')
if [ "$kill" != "" ]; then
kill $kill
fi
if [ -e /etc/adm/usuarios/$name ]; then
rm -rf /etc/adm/usuarios/$name
fi
echo -e "\033[1;32m-----------------------------\033[0m"
echo -e "\033[1;31m$name Removido\033[0m"
sleep 0.3s
done
echo -e "\033[1;32m------------------------------\033[0m"
rm -rf /tmp/ussh
 fi
fi
#--------------------------------------------------------------#

if [ "$1" = "adm5" ]; then
touch /tmp/qusers
echo -e "\033[1;30m------------------------------------------------------------\033[0m"
echo -e "\033[42;30m Usuario               Senha               Data E.          Logins\033[0m"
echo -e "\033[1;31mUSUARIOS OPENVPN/SSH SAO VERMELHOS!\033[0m"
echo -e "\033[1;30m------------------------------------------------------------\033[0m"
for namer in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
if [ -e /etc/adm/usuarios/$namer ]; then
temporario=$(cat /etc/adm/usuarios/$namer | grep "Minutos")
fi
if [ "$temporario" != "" ]; then
limitecs="Temporário"
senha=$(cat /etc/adm/usuarios/$namer | grep "senha" | awk '{print $2}')
data="Temporário"
else
if [ -e /etc/adm/usuarios/$namer ]; then
ovc=$(cat /etc/adm/usuarios/$namer | egrep -o OPENVPN)
senha=$(cat /etc/adm/usuarios/$namer | grep "senha" | awk '{print $2}')
limitecs=$(cat /etc/adm/usuarios/$namer | grep "limite" | awk '{print $2}')
fi
data=$(chage -l $namer |grep -i co |awk -F : '{print $2}')
echo "$namer" >> /tmp/qusers
if [ "$limitecs" = "" ]; then
limitecs="Sem Cadastro"
fi
if [ "$senha" = "" ]; then
senha="Sem Cadastro"
fi
if [ "$data" = "never" ]; then
data="Sem Cadastro"
fi
fi
detalhesdata=$(printf '%-18s' "$data")
detalheslimit=$(printf '%-10s' "$limitecs")
detalhes=$(printf ' %-21s' "$namer")
detalhespass=$(printf '%-18s' "$senha")
if [ "$ovc" = "" ]
then
echo -e "\033[1;33m$detalhes $detalhespass $detalhesdata $detalheslimit\033[0m"
else
echo -e "\033[1;31m$detalhes $detalhespass $detalhesdata $detalheslimit\033[0m"
fi
echo -e "\033[1;30m------------------------------------------------------------\033[0m"
done
cont=$(cat /tmp/qusers | wc -l)
echo
echo -e "\033[01;32mVOCE TEM UM TOTAL
DE:\033[00;37m" $cont
echo -e "\033[01;32mUSUARIOS EM SEU SERVIDOR!\033[00;37m"
rm -rf /tmp/qusers
exit
fi

#--------------------------------------------------------------#


if [ "$1" = "adm61" ]; then
while true; do
cat /etc/passwd |grep -v ovpn > /etc/adm/usr
clear
usr22=$(printf '%-18s' "LOGUINS")
usr11=$(printf ' %-21s' "USUARIO")
echo -e "\033[42;30m $usr11 $usr22\033[0m"
echo -e "\033[1;32m______________________________________"
for user in `awk -F : '$3 > 900 { print $1 }' /etc/adm/usr |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
num=$(dropb | grep "$user" | wc -l)
usr2=$(printf '%-18s' "$num")
usr1=$(printf ' %-21s' "$user")
echo -e "\033[1;33m$usr1     $usr2 \033[1;32m"
echo -e "______________________________________ "
done
rm -rf /etc/adm/usr
sleep 2s
exit
done
fi

if [ "$1" = "adm62" ]; then
cat /etc/passwd |grep -v ovpn > /etc/adm/usr
usr22=$(printf '%-18s' "LOGUINS")
usr11=$(printf ' %-21s' "USUARIO")
echo -e "\033[42;30m $usr11 $usr22\033[0m"
echo -e "\033[1;32m______________________________________"
for user in `awk -F : '$3 > 900 { print $1 }' /etc/adm/usr |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
num=$(dropb | grep "$user" | wc -l)
usr2=$(printf '%-18s' "$num")
usr1=$(printf ' %-21s' "$user")
echo -e "\033[1;33m$usr1     $usr2 \033[1;32m"
echo -e "______________________________________ "
done
echo -e "\033[42;30m $usr11 $usr22\033[0m"
rm -rf /etc/adm/usr
exit
fi

#--------------------------------------------------------------#

if [ "$1" = "adm7" ]; then
touch /tmp/ussh
cat /etc/passwd |grep -v ovpn > /tmp/ussh
datenow=$(date +%s)
tput setaf 7 ; tput setab 2 ; tput bold ; printf '%45s%-10s%-5s\n' "Removedor de contas expiradas" ""
printf '%-20s%-25s%-20s\n' "Usuário" "Data de expiração" "Estado/Ação" ; echo "" ; tput sgr0
for user in $(awk -F: '{print $1}' /tmp/ussh); do
expdate=$(chage -l $user|awk -F: '/Account expires/{print $2}')
echo $expdate|grep -q never && continue
datanormal=$(date -d"$expdate" '+%d/%m/%Y')
tput setaf 3 ; tput bold ; printf '%-20s%-21s%s' $user $datanormal ; tput sgr0
expsec=$(date +%s --date="$expdate")
diff=$(echo $datenow - $expsec|bc -l)
tput setaf 2 ; tput bold
echo $diff|grep -q ^\- && if [ "$expsec" -gt "$datenow" ]; then
datas=$(($expsec - $datenow))
DDD=$(($datas / 86400))
 if [ "$DDD" = "0" ]; then
day="Ultimo Dia Restante"
else
day="$DDD Dias Restantes"
 fi; echo "(Ativo) $day"
fi && continue
tput setaf 1 ; tput bold
echo "Expirado (Removido)"
pkill -f $user
userdel $user
userkill $user
rm -rf /etc/adm/usuarios/$user
sleep 0.4s
done
tput sgr0 
rm -rf /tmp/ussh
exit
fi

#--------------------------------------------------------------#

if [ "$1" = "adm81" ]; then
chk=$(cat /etc/ssh/sshd_config |grep Banner )
 if echo "$chk" |grep -v "#Banner" |grep Banner > /dev/null 2> /dev/null
then
local=$(echo "$chk" |grep -v "#Banner" |grep Banner |awk '{print $2}')
if [ -e $local ]; then
ban=$(cat $local) > /dev/null 2>&1
else
ban=""
fi
  if [ "$ban" = "" ]; then
ban="Nenhum"
  fi
echo -e "\033[1;32mBanner Atual:\033[1;31m $ban"
echo -e "\033[1;33mO que voce deseja por no banner ?\033[0m"
read -p ": " banner
echo "$banner" > $local
exit
 fi
echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
service ssh restart > /dev/null 2> /dev/null
service sshd restart > /dev/null 2> /dev/null
menu
fi

if [ "$1" = "adm82" ]; then
 if [ -e /etc/dropbear/ban ]; then
banatual=$(cat /etc/dropbear/ban)
else
touch /etc/dropbear/ban
banatual="Nenhum"
 fi
echo -e "\033[1;32mBanner Atual: \033[1;31m$banatual"
echo -e "\033[1;33mDigite Agora O Novo Banner!"
read -p ": " banner
echo -e "$banner" >> /etc/dropbear/ban
mv -f /etc/dropbear/ban /etc/dropbear/banner
service dropbear restart
echo -e "\033[1;33m
Agora A Mensagem Do Banner E \033[1;31m
$banner \033[0m"
exit
fi

#--------------------------------------------------------------#

if [ "$1" = "adm90" ]; then
rm -rf /root/usrh
touch /root/usrh
admfun vencido1
 if [ -e /etc/adm/modulo/ovpn ]; then
admfun vencido2
 fi
exit
fi

if [ "$1" = "vencido1" ]; then
touch /root/vencido
cat /etc/passwd |grep -v ovpn > /tmp/ussh
datenow=$(date +%s)
for user in $(awk -F: '{print $1}' /tmp/ussh)
do
expdate=$(chage -l $user|awk -F: '/Account expires/{print $2}')
echo $expdate|grep -q never && continue
datanormal=$(date -d"$expdate" '+%d/%m/%Y')
expsec=$(date +%s --date="$expdate")
diff=$(echo $datenow - $expsec|bc -l)
echo $diff|grep -q ^\- && echo "" && continue
echo "1" >> /root/vencido
done
usr=$(cat /root/vencido | wc -l)
echo -e "$usr Usuarios SSH Vencidos!" >> /root/usrh
rm -rf /tmp/ussh
rm -rf /root/vencido
fi

if [ "$1" = "vencido2" ]; then
touch /root/vencido
cat /etc/passwd |grep ovpn > /tmp/ussh
datenow=$(date +%s)
for user in $(awk -F: '{print $1}' /tmp/ussh)
do
expdate=$(chage -l $user|awk -F: '/Account expires/{print $2}')
echo $expdate|grep -q never && continue
datanormal=$(date -d"$expdate" '+%d/%m/%Y')
expsec=$(date +%s --date="$expdate")
diff=$(echo $datenow - $expsec|bc -l)
echo $diff|grep -q ^\- && echo "" && continue
echo "1" >> /root/vencido
done
usr=$(cat /root/vencido | wc -l)
echo -e "$usr Usuarios OPENVPN Vencidos!" >> /root/usrh
rm -rf /root/vencido
rm -rf /tmp/ussh
fi

#--------------------------------------------------------------#

if [ "$1" = "banner" ]; then
clear
apt-get install figlet -y > /dev/null 2>&1
echo -e "\033[1;31mESSE E O BANNER OCULTO!"
echo -e "\033[1;33mAdicionar ou Remover Banner Nos Menus?\033[0m"
read -p "[ adicionar/remover ]: " mmm
if [ "$mmm" = "remover" ]; then
rm -rf /etc/adm/bnr
echo -e "\033[0m"
exit
fi
if [ "$mmm" = "adicionar" ]; then
echo -e "\033[0m"
read -p "Digite A msg  Principal do Menu
MSG: " bnr1
echo -e "\033[1;31m[1] vermelho
\033[1;32m[2] verde
\033[1;33m[3] amarelo
\033[1;34m[4] azul esc
\033[1;35m[5] rosa
\033[1;36m[6] azul\033[0m"
read -p "Qual a Cor?: " cor1
read -p "Digite A msg  Secundaria do Menu
MSG: " bnr2
echo -e "\033[1;31m[1] vermelho
\033[1;32m[2] verde
\033[1;33m[3] amarelo
\033[1;34m[4] azul esc
\033[1;35m[5] rosa
\033[1;36m[6] azul\033[0m"
read -p "Qual a Cor?: " cor2
if [ "$cor1" = "1" ]; then
c1="\033[1;31m"
fi
if [ "$cor1" = "2" ]; then
c1="\033[1;32m"
fi
if [ "$cor1" = "3" ]; then
c1="\033[1;33m"
fi
if [ "$cor1" = "4" ]; then
c1="\033[1;34m"
fi
if [ "$cor1" = "5" ]; then
c1="\033[1;35m"
fi
if [ "$cor1" = "6" ]; then
c1="\033[1;36m"
fi
if [ "$cor2" = "1" ]; then
c2="\033[1;31m"
fi
if [ "$cor2" = "2" ]; then
c2="\033[1;32m"
fi
if [ "$cor2" = "3" ]; then
c2="\033[1;33m"
fi
if [ "$cor2" = "4" ]; then
c2="\033[1;34m"
fi
if [ "$cor2" = "5" ]; then
c2="\033[1;35m"
fi
if [ "$cor2" = "6" ]; then
c2="\033[1;36m"
fi
echo "#!/bin/bash" > /etc/adm/bnr
echo "echo -e '\033[0;35m--------------------------------------------------\033[0m'" >> /etc/adm/bnr
echo "echo -e '$c1'" >> /etc/adm/bnr
echo "figlet $bnr1" >> /etc/adm/bnr
echo "echo -e '$c2'" >> /etc/adm/bnr
echo "echo '$bnr2'" >> /etc/adm/bnr
echo "echo -e '\033[0m'" >> /etc/adm/bnr
chmod +x /etc/adm/bnr
else
echo -e "\033[0m"
exit
fi
fi

#--------------------------------------------------------------#



sleep 1s
exit
